import Head from 'next/head'
import styles from '../styles/Home.module.css'
import File from '../components/file'
import {dataTree} from '../data/dataTree';



export default function Home() {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
      <File {...dataTree} />
      </div>
    </div>
  )
}
